{
"parserOptions": {
  ecmaVersion: 2015,
  sourceType: 'module',
},
"env": {
  es6: true,
  browser: true,
  commonjs: true,
},
"extends": 'htmlacademy/es6',
"rules": {
"no-restricted-globals": ['error', 'event'],
"prefer-const": 'error',
"no-else-return": 'error'
}
}